### ISSUE TITLE
[FEAT] 멋사 10차 백엔드 과제🦁

### ISSUE THREAD

**Issue by dpfls0922** [Likelion-at-SMWU-11th/LeeYeRin#21]
## 📌 Feature Issue
<!— 과제에 대해 설명해주세요 —>
- CRUD 페이지 만들기
- 테킷 강의를 보며 update, delete 코드 구현하기

## 📝 To do
<!— 해야 할 일들을 적어주세요 —>
- [ ] 테킷 강의를 보며 update, delete 코드 구현하기

**Comment by nayujin-dev** [comment]
pr에 연결이 안되어서 저절로 안닫히네용
제가 닫을게요 ~
